# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BooksAPI' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BooksAPI

pod 'AFNetworking', '~> 3.0'

  target 'BooksAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BooksAPIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
